### ISSUE TITLE
Hive error Android 13

### ISSUE THREAD

**Issue by 31415pi** [cake-tech/cake_wallet#524] opened 2022-09-30 11:39 UTC
![Screenshot_20220930-043835](https://user-images.githubusercontent.com/31289154/193261881-56846969-77eb-497d-a31e-b6aba72e3ab2.png)

**Comment by 31415pi** [comment] 2022-09-30 17:13
Wallet app doesn't open even with reinstall. 
Pixel 6 pro
![Screenshot_20220930-101208](https://user-images.githubusercontent.com/31289154/193322320-27e03262-7918-43a0-9bd1-ec2205f85c02.png)

**Comment by SamsungGalaxyPlayer** [comment] 2022-10-28 15:50
Please contact Cake Wallet support with a request to join our beta Flutter build that has an upgraded Hive version. Alternatively, you can try using that release once it is fully rolled out.

* Email: support@cakewallet.com
* Telegram DM: https://t.me/cakewallet_bot
* Twitter DM: https://twitter.com/cakewallet

**Comment by SamsungGalaxyPlayer** [comment] 2022-10-28 15:51
Duplicate of https://github.com/cake-tech/cake_wallet/issues/191

**Closed by SamsungGalaxyPlayer** 2022-10-28 15:51 UTC
