### ISSUE TITLE
Cake Wallet HiveError iOS

### ISSUE THREAD

**Issue by Hamhead1267** [cake-tech/cake_wallet#519] opened 2022-09-23 03:19 UTC
When I open Cake Wallet it shows:
HiveError: This should not happen. Pleas open an issue on GitHub
I cannot access my wallet and need help.

**Comment by SamsungGalaxyPlayer** [comment] 2022-10-28 15:56
Duplicate of https://github.com/cake-tech/cake_wallet/issues/191

**Closed by SamsungGalaxyPlayer** 2022-10-28 15:56 UTC
