### ISSUE TITLE
Cake doesn't show selected tokens when the user comeback to the wallet from another wallet

### ISSUE THREAD

**Issue by serrq** [cake-tech/cake_wallet#1815] opened 2024-11-18 07:15 UTC
Android 14
OnePlus CPH2399
Cake 4.21.0 (Cake Labs repo)

![1000125815](https://github.com/user-attachments/assets/07aed5bc-ca47-4255-888d-dac40cf6d75d)

![1000125817](https://github.com/user-attachments/assets/949bbac4-9384-4877-8a39-8a8ce9599ea8)

**Comment by OmarHatem28** [comment] 2024-11-18 16:25
Deleted the comment from @Angiepeck22 as he is a scammer,
for your issue, the tokens usually don't show if the app failed to fetch the balance for them, so please check your network connection and let me know if this solves the issue
if not, please provide more info and steps to reproduce

**Comment by OmarHatem28** [comment] 2024-12-04 02:13
Closing this since there were no updates on it, but please feel free to re-open it if the issue still persists and provide more info and steps to reproduce
Thank you for your feedback

**Closed by OmarHatem28** 2024-12-04 02:13 UTC
Labels: Bug
