### ISSUE TITLE
HIVE ERROR ON ANDROID GALAXY S22

### ISSUE THREAD

**Issue by Forthelowitcango420** [cake-tech/cake_wallet#556] opened 2022-10-21 20:53 UTC
My Cake wallet is giving the same error as most is here! I've tried restoring my wallet on another phone but none of my funds have transfered nor are they showing up in my wallets anything that can be done to resolve this as I have about 6k sitting in your wallets atm

**Comment by SamsungGalaxyPlayer** [comment] 2022-10-28 15:50
Please contact Cake Wallet support with a request to join our beta Flutter build that has an upgraded Hive version. Alternatively, you can try using that release once it is fully rolled out.

* Email: support@cakewallet.com
* Telegram DM: https://t.me/cakewallet_bot
* Twitter DM: https://twitter.com/cakewallet

**Comment by SamsungGalaxyPlayer** [comment] 2022-10-28 15:52
Duplicate of https://github.com/cake-tech/cake_wallet/issues/191

**Closed by SamsungGalaxyPlayer** 2022-10-28 15:52 UTC
