### ISSUE TITLE
Automatic syncing and payment notifications

### ISSUE THREAD

**Issue by erib3** [cake-tech/cake_wallet#144] opened 2021-06-03 09:19 UTC
Is it possible to do automatic syncing with cake wallet? I am also interested in notifications being sent to me when a payment is received.

**Comment by SamsungGalaxyPlayer** [comment] 2022-10-28 16:41
Duplicate of https://github.com/cake-tech/cake_wallet/issues/275

**Closed by SamsungGalaxyPlayer** 2022-10-28 16:41 UTC
